# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json

name: ðŸ’¡ æˆ‘æœ‰ä¸ªæƒ³æ³•
<<<<<<< HEAD
description: å»ºè®®æ–°åŠŸèƒ½æˆ–æ”¹è¿›çŽ°æœ‰åŠŸèƒ½
=======
description: å»ºè®®æ–°åŠŸèƒ½ã€æŽ¨é€æ ·å¼æ”¹è¿›æˆ–ä½“éªŒä¼˜åŒ–
>>>>>>> upstream/master
title: "[å»ºè®®] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
<<<<<<< HEAD
        ### ðŸ’ æ¸©é¦¨æé†’

        æ„Ÿè°¢ä½ çš„åˆ›æ„æƒ³æ³•ï¼å¦‚æžœè¿™ä¸ªé¡¹ç›®å¯¹ä½ æœ‰å¸®åŠ©ï¼Œæ¬¢è¿Žç»™é¡¹ç›®ç‚¹ä¸ª â­ **Star**ï¼

        å¥½çš„å»ºè®®è®©é¡¹ç›®å˜å¾—æ›´åŠ å®žç”¨ã€‚**æ¬¢è¿Žç”¨æˆªå›¾æˆ–ç¤ºä¾‹**æ¥å±•ç¤ºä½ çš„æƒ³æ³•ï¼

  - type: dropdown
    id: feature-category
    attributes:
      label: ðŸ·ï¸ å»ºè®®ç±»åˆ«
      options:
        - æ•°æ®æºç›¸å…³ï¼ˆæ–°å¢žå¹³å°ã€æ”¹è¿›æŠ“å–ç­‰ï¼‰
        - åˆ†æžåŠŸèƒ½ç›¸å…³ï¼ˆç®—æ³•æ”¹è¿›ã€ç­›é€‰ä¼˜åŒ–ç­‰ï¼‰
        - é€šçŸ¥æ–¹å¼ç›¸å…³ï¼ˆæ–°å¢žé€šçŸ¥æ¸ é“ã€æ¶ˆæ¯æ ¼å¼ç­‰ï¼‰
        - é…ç½®ç®¡ç†ç›¸å…³ï¼ˆè®¾ç½®ä¼˜åŒ–ã€ç•Œé¢æ”¹è¿›ç­‰ï¼‰
        - éƒ¨ç½²è¿ç»´ç›¸å…³ï¼ˆå®‰è£…ç®€åŒ–ã€ç›‘æŽ§å‘Šè­¦ç­‰ï¼‰
        - æ•°æ®å±•ç¤ºç›¸å…³ï¼ˆæŠ¥å‘Šæ ¼å¼ã€å›¾è¡¨å¯è§†åŒ–ç­‰ï¼‰
        - æ€§èƒ½ä¼˜åŒ–ç›¸å…³
        - ç”¨æˆ·ä½“éªŒæ”¹è¿›
        - å…¶ä»–æƒ³æ³•
    validations:
      required: true
=======
        ### ðŸ’ æ¬¢è¿Žåˆ†äº«ä½ çš„åˆ›æ„
        ä½ çš„å¥½ç‚¹å­èƒ½è®© TrendRadar å˜å¾—æ›´å¥½ï¼
        
        ç›®å‰ä¸»è¦å…³æ³¨ä»¥ä¸‹æ–¹å‘çš„æ”¹è¿›ï¼š
        - âœ¨ **AI åˆ†æžèƒ½åŠ›**ï¼šæ›´æ™ºèƒ½çš„è§£è¯»ã€æ›´ä¸°å¯Œçš„åˆ†æžç»´åº¦
        - ðŸŽ¨ **æŽ¨é€ä½“éªŒ**ï¼šæ›´å¥½çœ‹çš„æŽ’ç‰ˆã€æ›´åˆç†çš„ä¿¡æ¯å±•ç¤º
        - ðŸ› ï¸ **æ˜“ç”¨æ€§ä¼˜åŒ–**ï¼šé…ç½®æ›´ç®€å•ã€è¿è¡Œæ›´ç¨³å®š
        
        *æ³¨ï¼šç›®å‰æš‚ä¸æŽ¥å—æ–°çˆ¬è™«å¹³å°çš„æŽ¥å…¥ç”³è¯·ï¼Œæ„Ÿè°¢ç†è§£ã€‚*
>>>>>>> upstream/master

  - type: textarea
    id: feature-description
    attributes:
<<<<<<< HEAD
      label: ðŸ’­ è¯¦ç»†æè¿°ä½ çš„æƒ³æ³•
      description: è¯·è¯¦ç»†æè¿°ä½ å¸Œæœ›æ·»åŠ çš„åŠŸèƒ½
      placeholder: |
        è¯·è¯¦ç»†æè¿°ï¼š
        - ä½ å¸Œæœ›å¢žåŠ ä»€ä¹ˆåŠŸèƒ½
        - è¿™ä¸ªåŠŸèƒ½åº”è¯¥æ€Žä¹ˆä½¿ç”¨
        - ä½¿ç”¨åŽèƒ½è¾¾åˆ°ä»€ä¹ˆæ•ˆæžœ

        ðŸ’¡ æç¤ºï¼šå¦‚æžœæœ‰ç±»ä¼¼åŠŸèƒ½çš„æˆªå›¾ä½œä¸ºå‚è€ƒå°±æ›´å¥½äº†ï¼
=======
      label: ðŸ’­ ä½ çš„æƒ³æ³•æ˜¯ä»€ä¹ˆï¼Ÿ
      placeholder: |
        è¯·ç®€è¦æè¿°ï¼š
        - ä½ å¸Œæœ›å¢žåŠ ä»€ä¹ˆåŠŸèƒ½ï¼Ÿ
        - å®ƒèƒ½è§£å†³ä»€ä¹ˆé—®é¢˜ï¼Ÿ
        - å¦‚æžœæœ‰å‚è€ƒçš„å›¾ç‰‡æˆ–å·¥å…·ï¼Œæ¬¢è¿Žä¸Šä¼ æˆªå›¾ã€‚
>>>>>>> upstream/master
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
<<<<<<< HEAD
      label: ðŸŽ¯ ä»€ä¹ˆæ—¶å€™ä¼šç”¨åˆ°è¿™ä¸ªåŠŸèƒ½
      description: è¿™ä¸ªåŠŸèƒ½åœ¨ä»€ä¹ˆåœºæ™¯ä¸‹ä½¿ç”¨ï¼Ÿ
      placeholder: |
        ä¾‹å¦‚ï¼š
        - å½“æˆ‘éœ€è¦...çš„æ—¶å€™
        - åœ¨...æƒ…å†µä¸‹ä¼šå¾ˆæ–¹ä¾¿
        - å¯ä»¥è§£å†³...é—®é¢˜
        - èƒ½å¤Ÿå¸®åŠ©...ç”¨æˆ·
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: ðŸ› ï¸ å®žçŽ°æƒ³æ³•ï¼ˆå¯é€‰ï¼‰
      description: å¦‚æžœä½ æœ‰å®žçŽ°æ€è·¯ï¼Œæ¬¢è¿Žåˆ†äº«
      placeholder: |
        - åŠŸèƒ½ç•Œé¢åº”è¯¥æ€Žä¹ˆè®¾è®¡
        - é…ç½®åº”è¯¥æ€Žä¹ˆè®¾ç½®
        - å‚è€ƒå“ªäº›ç±»ä¼¼çš„å·¥å…·æˆ–ç½‘ç«™
        - å…¶ä»–å®žçŽ°å»ºè®®

  - type: textarea
    id: mockups-examples
    attributes:
      label: ðŸ“· åŠŸèƒ½ç¤ºæ„å›¾ï¼ˆæŽ¨èï¼‰
      description: ä¸Šä¼ åŠŸèƒ½ç¤ºæ„å›¾ã€å‚è€ƒæˆªå›¾æˆ–æ‰‹ç»˜è‰å›¾
      placeholder: |
        è¯·ä¸Šä¼ ï¼š
        - åŠŸèƒ½ç•Œé¢çš„è®¾è®¡å›¾ï¼ˆæ‰‹ç»˜ä¹Ÿå¯ä»¥ï¼‰
        - ç±»ä¼¼åŠŸèƒ½çš„å‚è€ƒæˆªå›¾
        - ä½¿ç”¨æµç¨‹çš„ç¤ºæ„å›¾

        ðŸ’¡ å¯è§†åŒ–çš„è¯´æ˜Žæœ€å®¹æ˜“ç†è§£ï¼

  - type: textarea
    id: additional-context
    attributes:
      label: ðŸ“Ž å…¶ä»–è¡¥å……è¯´æ˜Ž
      description: å…¶ä»–æƒ³è¦è¡¥å……çš„å†…å®¹
      placeholder: |
        - ç›¸å…³çš„å‚è€ƒèµ„æ–™é“¾æŽ¥
        - ç±»ä¼¼åŠŸèƒ½çš„å…¶ä»–å·¥å…·
        - æ›´å¤šä½¿ç”¨åœºæ™¯è¯´æ˜Ž
        - å…¶ä»–ç›¸å…³æƒ³æ³•
=======
      label: ðŸŽ¯ ä½¿ç”¨åœºæ™¯ï¼ˆå¯é€‰ï¼‰
      placeholder: ä¾‹å¦‚ï¼šå½“æˆ‘åœ¨...çš„æ—¶å€™ï¼Œå¦‚æžœèƒ½...å°±å¤ªæ£’äº†ã€‚
    validations:
      required: false
>>>>>>> upstream/master
